### PR TITLE
Merged upstream  package used in Envoy 1.22

### PR DESCRIPTION
**Pull request by dcillera**
Merged proxy-wasm-cpp-host 694a0b0 - update to v0.35.2. (#283)

### CODE REVIEW

**Comment by oschaaf** [comment]
The last three commits seem like a touch-up to amend earlier conflict resolution, is that correct? If so, it would seem cleaner to me to correct the commits that needed conflict resolution so they apply/build correctly... what do you think? 

That aside, these also introduce some new files that I think we don't want (log files, .out files, etc). Can we strip those?

**Comment by oschaaf** [comment]
Sorry -- looking at this, and thinking about it once more, I wonder if rebasing the very few commits that we have in this fork on top of the revision that we want, could yield a much easier to review and understand end result?

**Comment by dcillera** [comment]
>

**Comment by dcillera** [comment]
> >

Yes, even if rebasing means to repeat the work.

**Comment by dcillera** [comment]
As requested by Otto, I have removed "rubbish" files and bundled all my commits into only one

**Review by jwendell — APPROVED** [review]
@dcillera did you test Envoy/Proxy using this branch? If yes, it LGTM.

**Comment by dcillera** [comment]
I've tested PROXY but not Envoy.

**Comment by jwendell** [comment]
Closing in favor of https://github.com/maistra/envoy/pull/195

**Pull request closed without merging**
